In [1]:
import numpy as np

In [20]:
class classical_DE(object):
    
    def __init__(self, n_gens=10, n_pop=10, n_dim=5, F=0.7, Cr=0.8, bounds=[-100, 100]):
        self.n_gens=n_gens
        self.n_pop=n_pop
        self.n_dim=n_dim
        self.F=F
        self.Cr=Cr
        self.bounds=bounds
        self
        
    def get_F(self):
        return self.F
    def get_Cr(self):
        return self.Cr
    def get_bounds(self):
        return self.bounds
    def get_population(self):
        return self.population
    
    def gen_rand(self, n_size=1):
        '''
        This function return a n_size-dimensional random vector.
        '''
        return np.random.random(n_size)

    def init_population(self, pop_size, dim=1, bounds=[-100,100]):
        '''
        This function initialize the population to be use in DE
        Arguments:
        pop_size - Number of individuals (there is no default value to this yet.).
        dim - dimension of the search space (default is 1).
        bounds - The inferior and superior limits respectively (default is [-100, 100]).
        '''
        return np.random.uniform(low=bounds[0], high=bounds[1], size=(pop_size, dim))

    def keep_bounds(self, pop, bounds=[-10, 10]):
        '''
        This function keep the population in the seach space
        Arguments:
        pop - Population;
        bounds - The inferior and superior limits respectively
        '''
        pop[pop<bounds[0]] = bounds[0]; pop[pop>bounds[1]] = bounds[1]
        return pop

    def rand_p(self, pop, p=1, F=0.7):
        '''
        This function is the rand/p mutation scheme, this is a generalization of rand/1 mutation scheme
         from the first DE paper (Storn and Price).
        Arguments:
        pop - Population;
        p - Number of diferences to be used;
        F - The F scale factor for the diferences (default is 0.7);
        '''

        choices = np.random.choice(pop.shape[0], 1+2*p, replace=False)
        diffs = 0
        for idiff in range(1, len(choices), 2):
            diffs += F*((pop[choices[idiff]]-pop[choices[idiff+1]]))
        return pop[choices[0]] + diffs

    def binomial_crossover(self, pop, Cr=0.5, mutation_type=rand_p, **kwargs):
        '''
        This function make the binomial crossover.
        Arguments:
        pop - Population;
        mutation_type - mutation scheme (default is ran_p);
        **kwargs - This is relative to the mutation scheme ex. rand_p needs p and F.
        '''

        K = np.random.choice(pop.shape[1])
        for ind in range(tmp.shape[0]):
            mutant = mutation_type(pop, **kwargs)
            for jnd in range(tmp.shape[1]):
                if jnd == K or gen_rand()<Cr:
                    tmp[ind][jnd] = mutant[jnd]
        return pop

In [21]:
DE = classical_DE()

In [22]:
DE.gen_rand()

array([ 0.83295147])

In [15]:
DE.get_Cr(), DE.get_bounds()

(0.8, [-100, 100])

In [2]:
def gen_rand(n_size=1):
    '''
    This function return a n_size-dimensional random vector.
    '''
    return np.random.random(n_size)

def init_population(pop_size, dim=1, bounds=[-100,100]):
    '''
    This function initialize the population to be use in DE
    Arguments:
    pop_size - Number of individuals (there is no default value to this yet.).
    dim - dimension of the search space (default is 1).
    bounds - The inferior and superior limits respectively (default is [-100, 100]).
    '''
    return np.random.uniform(low=bounds[0], high=bounds[1], size=(pop_size, dim))

def keep_bounds(pop, bounds=[-10, 10]):
    '''
    This function keep the population in the seach space
    Arguments:
    pop - Population;
    bounds - The inferior and superior limits respectively
    '''
    pop[pop<bounds[0]] = bounds[0]; pop[pop>bounds[1]] = bounds[1]
    return pop

def rand_p(pop, p=1, F=0.7):
    '''
    This function is the rand/p mutation scheme, this is a generalization of rand/1 mutation scheme
     from the first DE paper (Storn and Price).
    Arguments:
    pop - Population;
    p - Number of diferences to be used;
    F - The F scale factor for the diferences (default is 0.7);
    '''
    
    choices = np.random.choice(pop.shape[0], 1+2*p, replace=False)
    diffs = 0
    for idiff in range(1, len(choices), 2):
        diffs += F*((pop[choices[idiff]]-pop[choices[idiff+1]]))
    return pop[choices[0]] + diffs

def binomial_crossover(pop, Cr=0.5, mutation_type=rand_p, **kwargs):
    '''
    This function make the binomial crossover.
    Arguments:
    pop - Population;
    mutation_type - mutation scheme (default is ran_p);
    **kwargs - This is relative to the mutation scheme ex. rand_p needs p and F.
    '''
    
    K = np.random.choice(pop.shape[1])
    for ind in range(tmp.shape[0]):
        mutant = mutation_type(pop, **kwargs)
        for jnd in range(tmp.shape[1]):
            if jnd == K or gen_rand()<Cr:
                tmp[ind][jnd] = mutant[jnd]
    return pop

In [3]:
tmp = init_population(10, dim=5, bounds=[-5, 5])
tmp

array([[-3.71543271, -0.67394105, -1.93567198,  1.03331445, -1.73842802],
       [-1.88235016, -4.81339779, -1.06004517, -4.02431873,  2.11036404],
       [ 1.96754997,  0.22493664,  4.98045641, -1.12915174, -1.8126292 ],
       [ 4.42917366, -3.91034278, -0.45718355,  3.27162976, -2.12711462],
       [ 0.16739496,  2.19394215, -3.52260518, -4.15335773, -0.42086346],
       [ 4.26588424,  4.2829178 , -0.36273087,  3.88594004,  4.7133616 ],
       [ 3.83770622,  0.18715704,  2.20450095, -1.45123322,  2.7118068 ],
       [-2.83514276, -3.42556345, -1.7003802 , -4.14503897,  3.24028342],
       [-0.60887569, -0.91691128, -3.64248103, -2.61850748,  1.98154827],
       [ 2.60040312,  4.22199377,  0.79892207, -0.72732844, -4.74445625]])

In [5]:
binomial_crossover(tmp,Cr=0.2, mutation_type=rand_p, p=2, F=0.5)

array([[-3.71543271, -0.67394105, -1.93567198,  1.03331445,  3.81287712],
       [-1.88235016, -4.81339779, -1.06004517, -4.02431873,  3.10181432],
       [ 1.96754997, -2.3813149 ,  4.98045641, -1.12915174, -0.63049037],
       [ 4.42917366, -3.91034278, -0.45718355,  3.27162976,  7.7004335 ],
       [ 0.16739496,  2.19394215, -3.52260518, -4.15335773,  5.3193249 ],
       [ 4.26588424, -2.19969716, -0.36273087,  3.88594004,  0.87671282],
       [ 3.83770622,  0.18715704,  2.20450095, -1.45123322,  6.33784081],
       [-2.83514276, -3.42556345, -1.7003802 , -4.14503897,  0.20380777],
       [-0.60887569, -0.91691128, -3.64248103, -2.61850748, -2.48187301],
       [-3.49144982,  4.22199377,  0.79892207, -0.72732844,  3.51858568]])

In [ ]:
rand_p(pop=tmp, p=1, F=0.2)

In [ ]:
K = np.random.choice(tmp.shape[1])
K

In [ ]:
print(tmp)
for ind in range(tmp.shape[0]):
    mutant = rand_p(tmp, p=1, F=0.5)
    for jnd in range(tmp.shape[1]):
        if jnd == K or gen_rand()<0.6:
            #print(tmp[ind][jnd])
            tmp[ind][jnd] = mutant[jnd]
tmp

In [ ]:
of

In [ ]:
trials[trials==1] = rand_p(tmp, p=2, F=0.5)

In [ ]:
trials

In [ ]:
tmp[choices[0]]

In [ ]:
for odd in range(1, len(choices), 2):
    print(odd)

In [ ]:
d = 0
for idiff in range(1, len(choices), 2):
    d += 0.1*(tmp[choices[idiff]]-tmp[choices[idiff+1]])


In [ ]:
d

In [ ]:
tmp[choices[1],:]-tmp[choices[2],:], 0.1*(tmp[choices[1],:]-tmp[choices[2],:])

In [ ]:
tmp[choices[0],:] + 0.1*(tmp[choices[1],:]-tmp[choices[2],:])

In [ ]:
idxs = np.ma.masked_where(pop < -10., pop)
idxs

In [ ]:
pop[[idxs.tolist]] = -5.

In [ ]:
pop